### ISSUE TITLE
老哥，这个 Demo 各种崩啊。。。。

### ISSUE THREAD

**Issue by zicen** [LillteZheng/VideoDemo#1]

**Comment by LillteZheng** [comment]
报啥错误，你把自己的视频和路径配置了没

**Comment by zicen** [comment]
配置了，首先 AudioRecord 录音一点就蹦了，然后是 Camera 除了 1 可以拍照，其他的都失败了，然后是 MediaExtractor 解析视频也是直接失败，MediaCodec 解码也是直接蹦

**Comment by zicen** [comment]
我录了屏，可以留个联系方式发给你看下
