### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by duxiahui** [LillteZheng/VideoDemo#3]
![image](https://user-images.githubusercontent.com/48590151/208868643-bf5b748d-b735-468b-9207-0ba7f629218a.png)

**Comment by LillteZheng** [comment]
已修复

**Comment by duxiahui** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
